version: "3"
services:
  app:
    container_name: hhp-nestjs-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    links:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
