version: "2.2"
services:
  app:
    env_file:
      - .env.development
    environment:
      - DATABASE_HOST=postgres
    container_name: hhp-nestjs-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 128M

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    env_file:
      - .env.development
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G

volumes:
  app:
    driver: local
  postgres:
    driver: local
